services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file: .env
    depends_on:
      - mongo
    networks:
      - backend_network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
